In [4]:
import pandas as pd
df = pd.read_csv("/Users/suchismitarout/Downloads/finance_loan_portfolio_python_dataset.csv")
df.head()

,Record_ID,Customer_ID,Customer_Name,Age,Gender,City,Employment_Type,Annual_Income_INR,Credit_Score,Loan_Type,...,Late_Payment_Count,Default_Flag,Debt_to_Income_Ratio,Savings_Balance_INR,Investment_Value_INR,Risk_Category,Last_Payment_Date,Payment_Mode,Acquisition_Channel,Branch_Name
0,FIN-00255,CUST-00839,Arjun Gupta,64.0,Female,Jaipur,Self-Employed,679000.0,707.0,Home Loan,...,7,Yes,0.920,42160.72,78362.21,High,2026-05-30,Auto-Debit,Partner,Nagpur Civil Lines
1,FIN-00474,CUST-00508,Rohan Iyer,63.0,Male,Mumbai,Salaried,1275000.0,745.0,Personal Loan,...,0,No,0.386,167007.37,435254.86,Low,2026-07-10,Net Banking,Website,Chennai T Nagar
2,FIN-00725,CUST-00013,Rohan Jadhav,48.0,Female,Lucknow,Government Employee,1390000.0,663.0,Personal Loan,...,2,No,NaN,6378.50,0.00,Low,NaN,UPI,Branch,Nashik Road
3,FIN-00438,CUST-00328,Tanvi Chaudhary,56.0,Male,Nashik,Government Employee,719000.0,695.0,Vehicle Loan,...,1,No,0.689,353397.61,148295.33,Medium,2026-06-24,Auto-Debit,Website,Delhi Connaught Place
4,FIN-00661,CUST-00740,Rahul Iyer,53.0,Female,Nashik,Business Owner,7218000.0,665.0,Home Loan,...,3,No,0.075,1210618.96,1460036.03,Medium,2026-04-24,UPI,Branch,Jaipur C Scheme

In [6]:
df["Age"] = df ["Age"].fillna(df ["Age"].mean())

In [8]:
df ["Annual_Income_INR"] = df ["Annual_Income_INR"].fillna(df ["Annual_Income_INR"].mean())

In [10]:
df ["Gender"]= df ["Gender"].fillna ("Unknown Gender")

In [11]:

df["Credit_Score"] = df["Credit_Score"].fillna(df["Credit_Score"].mean())

df["Interest_Rate_Pct"] = df["Interest_Rate_Pct"].fillna(df["Interest_Rate_Pct"].mean())

df["Outstanding_Balance_INR"] = df["Outstanding_Balance_INR"].fillna(df["Outstanding_Balance_INR"].mean())

df["Debt_to_Income_Ratio"] = df["Debt_to_Income_Ratio"].fillna(df["Debt_to_Income_Ratio"].mean())

df["Savings_Balance_INR"] = df["Savings_Balance_INR"].fillna(df["Savings_Balance_INR"].mean())

df["Investment_Value_INR"] = df["Investment_Value_INR"].fillna(df["Investment_Value_INR"].mean())

In [12]:
print(df.isnull().sum())

Record_ID                   0
Customer_ID                 0
Customer_Name               0
Age                         0
Gender                      0
City                       32
Employment_Type            25
Annual_Income_INR           0
Credit_Score                0
Loan_Type                   0
Loan_Amount_INR             0
Interest_Rate_Pct           0
Loan_Term_Months            0
Monthly_EMI_INR             0
Disbursement_Date           0
Outstanding_Balance_INR     0
Payment_Status              0
Days_Past_Due               0
Late_Payment_Count          0
Default_Flag                0
Debt_to_Income_Ratio        0
Savings_Balance_INR         0
Investment_Value_INR        0
Risk_Category               0
Last_Payment_Date          27
Payment_Mode               20
Acquisition_Channel         0
Branch_Name                 0
dtype: int64

In [13]:
print(df.duplicated().sum())

30

In [15]:
df = df.drop_duplicates()

In [16]:
print(df.duplicated().sum())

0

In [17]:
df.shape

(1200, 28)

In [18]:
#unique values in each object column

df['Gender'].unique()

array(['Female', 'Male', 'Non-Binary', 'Unknown Gender'], dtype=object)

In [19]:
df['Gender'].nunique()

4

In [20]:
df['Gender'].value_counts()

Gender
Male              584
Female            565
Non-Binary         29
Unknown Gender     22
Name: count, dtype: int64

In [21]:
df["Risk_Category"].unique()

array(['High', 'Low', 'Medium'], dtype=object)

In [23]:
df["Risk_Category"].nunique()

3

In [24]:
df["Risk_Category"].value_counts()

Risk_Category
Medium    504
Low       494
High      202
Name: count, dtype: int64

In [28]:
df["City"].unique()

array(['Jaipur', 'Mumbai', 'Lucknow', 'Nashik', 'Chennai', 'Delhi',
       'Indore', 'Ahmedabad', 'Bengaluru', nan, 'Hyderabad', 'Pune',
       'Thane', 'Surat', 'Kolkata', 'Nagpur'], dtype=object)

In [26]:
df["City"].nunique()

15

In [27]:
df["City"].value_counts()

City
Mumbai       217
Pune         166
Bengaluru     85
Delhi         81
Thane         74
Hyderabad     69
Nashik        62
Nagpur        62
Chennai       59
Surat         53
Jaipur        50
Lucknow       49
Kolkata       49
Indore        47
Ahmedabad     46
Name: count, dtype: int64

In [29]:
df["Payment_Mode"].unique()

array(['Auto-Debit', 'Net Banking', 'UPI', 'Cheque', 'Cash', nan],
      dtype=object)

In [30]:
df["Payment_Mode"].nunique()

5

In [31]:
df["Payment_Mode"].value_counts()

Payment_Mode
Auto-Debit     461
UPI            311
Net Banking    201
Cheque         121
Cash            86
Name: count, dtype: int64

In [32]:
#groupby() Used in order to group the data based on aggregate function (mean, max, min,count)

In [33]:
df.columns

Index(['Record_ID', 'Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City',
       'Employment_Type', 'Annual_Income_INR', 'Credit_Score', 'Loan_Type',
       'Loan_Amount_INR', 'Interest_Rate_Pct', 'Loan_Term_Months',
       'Monthly_EMI_INR', 'Disbursement_Date', 'Outstanding_Balance_INR',
       'Payment_Status', 'Days_Past_Due', 'Late_Payment_Count', 'Default_Flag',
       'Debt_to_Income_Ratio', 'Savings_Balance_INR', 'Investment_Value_INR',
       'Risk_Category', 'Last_Payment_Date', 'Payment_Mode',
       'Acquisition_Channel', 'Branch_Name'],
      dtype='object')

In [34]:
df.groupby("Gender")["Annual_Income_INR"].mean()

Gender
Female            1.368431e+06
Male              1.398722e+06
Non-Binary        1.570141e+06
Unknown Gender    1.574868e+06
Name: Annual_Income_INR, dtype: float64

In [35]:
df.groupby("Gender")["Annual_Income_INR"].max()

Gender
Female            7218000.0
Male              7292000.0
Non-Binary        4404000.0
Unknown Gender    3652000.0
Name: Annual_Income_INR, dtype: float64

In [37]:
df.groupby("Loan_Type")["Loan_Amount_INR"].sum()

Loan_Type
Business Loan     338690000
Education Loan    169825000
Gold Loan          53425000
Home Loan         937635000
Personal Loan     187300000
Vehicle Loan      323160000
Name: Loan_Amount_INR, dtype: int64

In [38]:
df.groupby (["Loan_Type", "Risk_Category"]) ["Loan_Amount_INR"].sum()

Loan_Type       Risk_Category
Business Loan   High              87005000
                Low               48055000
                Medium           203630000
Education Loan  High              58830000
                Low               57480000
                Medium            53515000
Gold Loan       High               1240000
                Low               18480000
                Medium            33705000
Home Loan       High             383155000
                Low              144405000
                Medium           410075000
Personal Loan   High              26700000
                Low               82290000
                Medium            78310000
Vehicle Loan    High              71910000
                Low              106720000
                Medium           144530000
Name: Loan_Amount_INR, dtype: int64

In [39]:
df.groupby (["Loan_Type", "Risk_Category"]) ["Loan_Amount_INR"].sum().sort_values(ascending=False)

Loan_Type       Risk_Category
Home Loan       Medium           410075000
                High             383155000
Business Loan   Medium           203630000
Vehicle Loan    Medium           144530000
Home Loan       Low              144405000
Vehicle Loan    Low              106720000
Business Loan   High              87005000
Personal Loan   Low               82290000
                Medium            78310000
Vehicle Loan    High              71910000
Education Loan  High              58830000
                Low               57480000
                Medium            53515000
Business Loan   Low               48055000
Gold Loan       Medium            33705000
Personal Loan   High              26700000
Gold Loan       Low               18480000
                High               1240000
Name: Loan_Amount_INR, dtype: int64

# Analytical Questions
## 1. How many total loan records are present in the cleaned dataset?

In [2]:
import pandas as pd
df = pd.read_csv("/Users/suchismitarout/Downloads/finance_loan_portfolio_python_dataset.csv")
len(df)

1230

## 2. How many unique customers are present in the dataset?

In [2]:
df['Customer_ID'].nunique()

653

## 3. How many customers have more than one loan record?

In [34]:
(df['Customer_ID'].value_counts() > 1).sum()

np.int64(355)

## 4. What are the unique loan types available in the dataset?

In [4]:
df['Loan_Type'].unique()

array(['Home Loan', 'Personal Loan', 'Vehicle Loan', 'Gold Loan',
       'Education Loan', 'Business Loan'], dtype=object)

## 5. How many unique cities, branches and employment categories are represented?

In [35]:
df[['City', 'Branch_Name', 'Employment_Type']].nunique()

City               15
Branch_Name        10
Employment_Type     5
dtype: int64

## 6. How many loan records belong to each loan type?

In [36]:
df['Loan_Type'].value_counts()

Loan_Type
Personal Loan     362
Vehicle Loan      250
Home Loan         210
Business Loan     171
Education Loan    123
Gold Loan         114
Name: count, dtype: int64

## 7. What percentage of the total loan records belongs to each loan type?

In [59]:
(df['Loan_Type'].value_counts() / len(df) * 100)

Loan_Type
Personal Loan     29.430894
Vehicle Loan      20.325203
Home Loan         17.073171
Business Loan     13.902439
Education Loan    10.000000
Gold Loan          9.268293
Name: count, dtype: float64

## 8. Which loan type has the highest and lowest number of loan records?

In [38]:
df['Loan_Type'].value_counts().idxmax(), df['Loan_Type'].value_counts().idxmin()

('Personal Loan', 'Gold Loan')

## 9. How many loan accounts fall under each payment-status category?

In [39]:
df['Payment_Status'].value_counts()

Payment_Status
On Time    398
Closed     394
Late       235
Missed     203
Name: count, dtype: int64

## 10. What percentage of accounts are on time, late, missed or closed?

In [3]:
(df['Payment_Status'].value_counts() / len(df) * 100)

Payment_Status
On Time    32.357724
Closed     32.032520
Late       19.105691
Missed     16.504065
Name: count, dtype: float64

## 11. How many accounts fall under each risk category?

In [41]:
df['Risk_Category'].value_counts()

Risk_Category
Medium    514
Low       506
High      210
Name: count, dtype: int64

## 12. What percentage of loan accounts are marked as defaulted?

In [5]:
(df['Default_Flag'].value_counts() / len(df) * 100)

Default_Flag
No     82.03252
Yes    17.96748
Name: count, dtype: float64

## 13. Which five cities have the highest number of loan accounts?

In [6]:
df['City'].value_counts().head(5)

City
Mumbai       221
Pune         169
Bengaluru     88
Delhi         82
Thane         74
Name: count, dtype: int64

## 14. How many unique customers are present in each city?

In [44]:
df.groupby('City')['Customer_ID'].nunique()

City
Ahmedabad     46
Bengaluru     81
Chennai       57
Delhi         78
Hyderabad     69
Indore        45
Jaipur        48
Kolkata       47
Lucknow       47
Mumbai       189
Nagpur        60
Nashik        57
Pune         152
Surat         51
Thane         71
Name: Customer_ID, dtype: int64

## 15. Which employment type has the highest number of borrowers?

In [45]:
df['Employment_Type'].value_counts().idxmax()

'Salaried'

## 16. Which payment mode is used most frequently?

In [29]:
df["Payment_Mode"].value_counts().idxmax()

'Auto-Debit'

## 17. Which acquisition channel generates the highest number of loan records?

In [33]:
df["Acquisition_Channel"].value_counts().idxmax()

'Mobile App'

## 18. Which five branches handle the highest number of loan accounts?

In [16]:
df['Branch_Name'].value_counts().head(5)

Branch_Name
Nagpur Civil Lines       134
Pune Central             133
Nashik Road              132
Bengaluru MG Road        125
Ahmedabad Navrangpura    123
Name: count, dtype: int64

## 19. What is the total sanctioned loan amount for each loan type?

In [48]:
df.groupby('Loan_Type')['Loan_Amount_INR'].sum()

Loan_Type
Business Loan     349790000
Education Loan    173205000
Gold Loan          55000000
Home Loan         954995000
Personal Loan     190950000
Vehicle Loan      335235000
Name: Loan_Amount_INR, dtype: int64

## 20. Which loan type has the highest total sanctioned loan amount?

In [49]:
df.groupby('Loan_Type')['Loan_Amount_INR'].sum().idxmax()

'Home Loan'

## 21. What are the average and median loan amounts for each loan type?

In [25]:
df.groupby('Loan_Type')['Loan_Amount_INR'].agg(['mean', 'median'])

                        mean     median
Loan_Type
Business Loan   2.045556e+06  1840000.0
Education Loan  1.408171e+06  1315000.0
Gold Loan       4.824561e+05   387500.0
Home Loan       4.547595e+06  4202500.0
Personal Loan   5.274862e+05   460000.0
Vehicle Loan    1.340940e+06  1210000.0

## 22. What are the minimum and maximum loan amounts for each loan type?

In [26]:
df.groupby('Loan_Type')['Loan_Amount_INR'].agg(['min', 'max'])

                   min       max
Loan_Type
Business Loan   250000   5400000
Education Loan  140000   3735000
Gold Loan        45000   1420000
Home Loan       920000  11270000
Personal Loan    65000   1430000
Vehicle Loan    185000   3120000

## 23. What is the average interest rate for each loan type?

In [50]:
df.groupby('Loan_Type')['Interest_Rate_Pct'].mean()

Loan_Type
Business Loan     16.919398
Education Loan    11.744750
Gold Loan         13.551712
Home Loan          9.485192
Personal Loan     16.690251
Vehicle Loan      11.804234
Name: Interest_Rate_Pct, dtype: float64

## 24. Which loan type has the highest average monthly EMI?

In [51]:
df.groupby('Loan_Type')['Monthly_EMI_INR'].mean().idxmax()

'Business Loan'

## 25. What is the total outstanding balance for each loan type?

In [52]:
df.groupby('Loan_Type')['Outstanding_Balance_INR'].sum()

Loan_Type
Business Loan     1.340983e+08
Education Loan    1.126396e+08
Gold Loan         7.911885e+06
Home Loan         7.760354e+08
Personal Loan     6.431382e+07
Vehicle Loan      1.527214e+08
Name: Outstanding_Balance_INR, dtype: float64

## 26. Which payment-status category has the highest total outstanding balance?

In [53]:
df.groupby('Payment_Status')['Outstanding_Balance_INR'].sum().idxmax()

'Missed'

## 27. What is the average outstanding balance for on-time, late, missed and closed accounts?

In [54]:
df.groupby('Payment_Status')['Outstanding_Balance_INR'].mean()

Payment_Status
Closed     0.000000e+00
Late       1.774464e+06
Missed     2.243286e+06
On Time    1.015307e+06
Name: Outstanding_Balance_INR, dtype: float64

## 28. What is the average credit score for each loan type?

In [55]:
df.groupby('Loan_Type')['Credit_Score'].mean()

Loan_Type
Business Loan     681.230303
Education Loan    679.149123
Gold Loan         674.612613
Home Loan         683.593137
Personal Loan     684.051429
Vehicle Loan      693.512295
Name: Credit_Score, dtype: float64

## 29. What is the average credit score for each employment category?

In [56]:
df.groupby('Employment_Type')['Credit_Score'].mean()

Employment_Type
Business Owner         692.560241
Freelancer             661.792857
Government Employee    701.887931
Salaried               689.410112
Self-Employed          671.461538
Name: Credit_Score, dtype: float64

## 30. What are the average and median annual incomes for each employment category?

In [57]:
df.groupby('Employment_Type')['Annual_Income_INR'].agg(['mean', 'median'])

                             mean     median
Employment_Type
Business Owner       2.997306e+06  2713000.0
Freelancer           8.904681e+05   877000.0
Government Employee  1.039000e+06  1000000.0
Salaried             1.070295e+06   982000.0
Self-Employed        1.426779e+06  1388000.0

## 31. What is the average debt-to-income ratio for each risk category?

In [58]:
df.groupby('Risk_Category')['Debt_to_Income_Ratio'].mean()

Risk_Category
High      0.774320
Low       0.324634
Medium    0.631638
Name: Debt_to_Income_Ratio, dtype: float64

## 32. How do average credit score, annual income and loan amount vary across risk categories?

In [7]:
df.groupby('Risk_Category')[['Credit_Score', 'Annual_Income_INR', 'Loan_Amount_INR']].mean()

               Credit_Score  Annual_Income_INR  Loan_Amount_INR
Risk_Category
High             636.542289       9.469369e+05     3.095548e+06
Low              719.879346       1.707707e+06     9.370751e+05
Medium           668.333333       1.253651e+06     1.818969e+06

## 33. How many high-risk loan accounts are present in each city?

In [8]:
df[df['Risk_Category'] == 'High']['City'].value_counts()

City
Pune         40
Mumbai       31
Bengaluru    18
Delhi        14
Nashik       14
Nagpur       13
Lucknow      12
Chennai      12
Thane        10
Indore        9
Ahmedabad     8
Surat         7
Kolkata       7
Jaipur        6
Hyderabad     5
Name: count, dtype: int64

## 34. Which loan type has the highest number of defaulted accounts?

In [ ]:
df[df['Default_Flag'] == 'Yes']['Loan_Type'].value_counts().idxmax()

## 35. What is the default percentage for each loan type?

In [9]:
(df[df['Default_Flag'] == 'Yes']['Loan_Type'].value_counts() / df['Loan_Type'].value_counts() * 100)

Loan_Type
Business Loan     20.467836
Education Loan    22.764228
Gold Loan          1.754386
Home Loan         35.238095
Personal Loan     10.773481
Vehicle Loan      17.200000
Name: count, dtype: float64

## 36. Which employment category has the highest default percentage?

In [10]:
(df[df['Default_Flag'] == 'Yes']['Employment_Type'].value_counts() / df['Employment_Type'].value_counts() * 100)

Employment_Type
Business Owner          7.558140
Freelancer             40.410959
Government Employee    12.396694
Salaried               16.123188
Self-Employed          17.757009
Name: count, dtype: float64

## 37. Which loan type has the highest number of late or missed-payment accounts?

In [11]:
df[df['Payment_Status'].isin(['Late', 'Missed'])]['Loan_Type'].value_counts().idxmax()

'Home Loan'

## 38. What are the top ten customers by total sanctioned loan amount?

In [12]:
df.groupby(['Customer_ID', 'Customer_Name'])['Loan_Amount_INR'].sum().sort_values(ascending=False).head(10)

Customer_ID  Customer_Name
CUST-00267   Kavya Sharma      11270000
CUST-00223   Kabir Kulkarni    10515000
CUST-00080   Divya Verma       10445000
CUST-00049   Vedant Iyer       10365000
CUST-00318   Mohit Nair        10195000
CUST-00217   Riya Sharma        9890000
CUST-00541   Priya Deshmukh     9865000
CUST-00362   Rohan Malhotra     9445000
CUST-00873   Yash Singh         9355000
CUST-00167   Sneha Bansal       9180000
Name: Loan_Amount_INR, dtype: int64

## 39. What are the top ten loan accounts by outstanding balance?

In [13]:
df.sort_values(by='Outstanding_Balance_INR', ascending=False).head(10)[['Record_ID', 'Customer_Name', 'Loan_Type', 'Outstanding_Balance_INR']]

      Record_ID   Customer_Name  Loan_Type  Outstanding_Balance_INR
417   FIN-00900    Kavya Sharma  Home Loan              10477485.47
486   FIN-00321     Vedant Iyer  Home Loan              10365000.00
667   FIN-00185      Mohit Nair  Home Loan              10043626.05
1001  FIN-00002  Priya Deshmukh  Home Loan               9829137.88
55    FIN-00061  Kabir Kulkarni  Home Loan               9396874.88
1113  FIN-01082     Divya Verma  Home Loan               9318080.54
429   FIN-00722     Sneha Mehta  Home Loan               8945000.00
1154  FIN-01153   Kiran Agarwal  Home Loan               8855734.09
343   FIN-00591  Rohan Malhotra  Home Loan               8730789.79
654   FIN-01110      Arjun Nair  Home Loan               8696670.39

## 40. How do the number and total value of loan disbursements vary by year and loan type?

In [18]:
df['Disbursement_Date'] = pd.to_datetime(df['Disbursement_Date'])

In [19]:
df['Disbursement_Year'] = df['Disbursement_Date'].dt.year

In [24]:
df.groupby(["Disbursement_Year", "Loan_Type"]).agg(No_of_Loans=("Record_ID","count"),
Total_Loan_Value = ("Loan_Amount_INR","sum"))

                                  No_of_Loans  Total_Loan_Value
Disbursement_Year Loan_Type
2021              Business Loan            38          79160000
                  Education Loan           34          52090000
                  Gold Loan                19          10740000
                  Home Loan                41         194020000
                  Personal Loan            70          33425000
                  Vehicle Loan             53          67670000
2022              Business Loan            32          65820000
                  Education Loan           22          36065000
                  Gold Loan                25          13500000
                  Home Loan                31         147580000
                  Personal Loan            63          29080000
                  Vehicle Loan             49          68810000
2023              Business Loan            32          69005000
                  Education Loan           28          32840000
                  Gold Loan                23           9505000
                  Home Loan                34         165855000
                  Personal Loan            63          34715000
                  Vehicle Loan             46          59480000
2024              Business Loan            27          57445000
                  Education Loan           17          24105000
                  Gold Loan                17           7795000
                  Home Loan                40         161935000
                  Personal Loan            64          37755000
                  Vehicle Loan             42          54075000
2025              Business Loan            28          51885000
                  Education Loan           13          15885000
                  Gold Loan                20           8815000
                  Home Loan                43         185120000
                  Personal Loan            70          37810000
                  Vehicle Loan             41          55385000
2026              Business Loan            14          26475000
                  Education Loan            9          12220000
                  Gold Loan                10           4645000
                  Home Loan                21         100485000
                  Personal Loan            32          18165000
                  Vehicle Loan             19          29815000