# Warehouse_Inventory_Clustering_dataset

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("/Users/suchismitarout/Downloads/warehouse_inventory_clustering_dataset.csv")

In [4]:
df.head()

,item_id,category,subcategory,supplier_id,warehouse_zone,avg_monthly_demand,demand_variability,avg_lead_time_days,lead_time_variability,monthly_reorder_count,...,damage_rate,holding_cost_per_unit,unit_cost,reorder_point_breaches,supplier_delay_incidents,current_stock,safety_stock,excess_stock_level,inventory_value,warehouse_demand_pressure_index
0,ITM00001,Grocery,Snacks,S1036,B2,310,0.26,7.8,0.05,8,...,0.012,10.83,132.98,1,2,249,75,46,33112.02,161.12
1,ITM00002,Industrial,Electrical Parts,S1036,B1,455,0.16,4.8,0.08,8,...,0.007,45.57,1525.56,0,0,362,94,34,552252.72,141.27
2,ITM00003,Apparel,Jackets,S1011,B2,350,0.43,20.9,0.57,6,...,0.010,18.47,457.56,3,9,317,105,146,145046.52,238.29
3,ITM00004,Automotive,Lubricants,S1030,A1,121,0.33,4.6,0.12,1,...,0.017,168.71,1779.38,0,1,183,32,84,325626.54,87.90
4,ITM00005,Pharmaceutical,Medical Devices,S1064,A2,85,0.14,7.3,0.15,1,...,0.016,33.33,731.83,2,4,209,17,180,152952.47,86.85

In [5]:
df.tail()

,item_id,category,subcategory,supplier_id,warehouse_zone,avg_monthly_demand,demand_variability,avg_lead_time_days,lead_time_variability,monthly_reorder_count,...,damage_rate,holding_cost_per_unit,unit_cost,reorder_point_breaches,supplier_delay_incidents,current_stock,safety_stock,excess_stock_level,inventory_value,warehouse_demand_pressure_index
3995,ITM03996,Pharmaceutical,OTC Medicine,S1003,C2,61,0.33,7.3,0.35,3,...,0.019,12.12,404.91,0,0,274,16,248,110945.34,28.77
3996,ITM03997,Automotive,Batteries,S1007,C1,487,0.40,13.8,0.50,6,...,0.026,45.95,844.98,10,5,371,141,18,313487.58,245.03
3997,ITM03998,Industrial,Fasteners,S1064,D2,32,0.61,10.9,0.36,2,...,0.020,60.67,1743.43,2,2,200,12,174,348686.00,56.08
3998,ITM03999,Stationery,Writing Tools,S1056,D1,571,0.42,11.8,0.41,11,...,0.015,4.62,132.21,5,12,511,170,52,67559.31,200.31
3999,ITM04000,Pharmaceutical,OTC Medicine,S1022,A1,540,0.13,6.4,0.08,7,...,0.018,11.49,218.83,2,1,453,106,8,99129.99,130.47

In [6]:
df.shape

(4000, 25)

In [7]:
df.columns

Index(['item_id', 'category', 'subcategory', 'supplier_id', 'warehouse_zone',
       'avg_monthly_demand', 'demand_variability', 'avg_lead_time_days',
       'lead_time_variability', 'monthly_reorder_count',
       'stock_turnover_ratio', 'days_in_inventory', 'stockout_frequency',
       'backorder_frequency', 'return_rate', 'damage_rate',
       'holding_cost_per_unit', 'unit_cost', 'reorder_point_breaches',
       'supplier_delay_incidents', 'current_stock', 'safety_stock',
       'excess_stock_level', 'inventory_value',
       'warehouse_demand_pressure_index'],
      dtype='object')

In [8]:
df.info

<bound method DataFrame.info of        item_id        category       subcategory supplier_id warehouse_zone  \
0     ITM00001         Grocery            Snacks       S1036             B2
1     ITM00002      Industrial  Electrical Parts       S1036             B1
2     ITM00003         Apparel           Jackets       S1011             B2
3     ITM00004      Automotive        Lubricants       S1030             A1
4     ITM00005  Pharmaceutical   Medical Devices       S1064             A2
...        ...             ...               ...         ...            ...
3995  ITM03996  Pharmaceutical      OTC Medicine       S1003             C2
3996  ITM03997      Automotive         Batteries       S1007             C1
3997  ITM03998      Industrial         Fasteners       S1064             D2
3998  ITM03999      Stationery     Writing Tools       S1056             D1
3999  ITM04000  Pharmaceutical      OTC Medicine       S1022             A1

      avg_monthly_demand  demand_variability  avg_lead_time_days  \
0                    310                0.26                 7.8
1                    455                0.16                 4.8
2                    350                0.43                20.9
3                    121                0.33                 4.6
4                     85                0.14                 7.3
...                  ...                 ...                 ...
3995                  61                0.33                 7.3
3996                 487                0.40                13.8
3997                  32                0.61                10.9
3998                 571                0.42                11.8
3999                 540                0.13                 6.4

      lead_time_variability  monthly_reorder_count  ...  damage_rate  \
0                      0.05                      8  ...        0.012
1                      0.08                      8  ...        0.007
2                      0.57                      6  ...        0.010
3                      0.12                      1  ...        0.017
4                      0.15                      1  ...        0.016
...                     ...                    ...  ...          ...
3995                   0.35                      3  ...        0.019
3996                   0.50                      6  ...        0.026
3997                   0.36                      2  ...        0.020
3998                   0.41                     11  ...        0.015
3999                   0.08                      7  ...        0.018

      holding_cost_per_unit  unit_cost  reorder_point_breaches  \
0                     10.83     132.98                       1
1                     45.57    1525.56                       0
2                     18.47     457.56                       3
3                    168.71    1779.38                       0
4                     33.33     731.83                       2
...                     ...        ...                     ...
3995                  12.12     404.91                       0
3996                  45.95     844.98                      10
3997                  60.67    1743.43                       2
3998                   4.62     132.21                       5
3999                  11.49     218.83                       2

      supplier_delay_incidents  current_stock  safety_stock  \
0                            2            249            75
1                            0            362            94
2                            9            317           105
3                            1            183            32
4                            4            209            17
...                        ...            ...           ...
3995                         0            274            16
3996                         5            371           141
3997                         2            200            12
3998                        12            511           170
3999                         1            453           106

      excess_stock_level  inventory_value  warehouse_demand_pressure_index
0                     46         33112.02                           161.12
1                     34        552252.72                           141.27
2                    146        145046.52                           238.29
3                     84        325626.54                            87.90
4                    180        152952.47                            86.85
...                  ...              ...                              ...
3995                 248        110945.34                            28.77
3996                  18        313487.58                           245.03
3997                 174        348686.00                            56.08
3998                  52         67559.31                           200.31
3999                   8         99129.99                           130.47

[4000 rows x 25 columns]>

In [9]:
df.isnull().sum()

item_id                            0
category                           0
subcategory                        0
supplier_id                        0
warehouse_zone                     0
avg_monthly_demand                 0
demand_variability                 0
avg_lead_time_days                 0
lead_time_variability              0
monthly_reorder_count              0
stock_turnover_ratio               0
days_in_inventory                  0
stockout_frequency                 0
backorder_frequency                0
return_rate                        0
damage_rate                        0
holding_cost_per_unit              0
unit_cost                          0
reorder_point_breaches             0
supplier_delay_incidents           0
current_stock                      0
safety_stock                       0
excess_stock_level                 0
inventory_value                    0
warehouse_demand_pressure_index    0
dtype: int64

In [10]:
df.isnull().sum().sum()

np.int64(0)

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.describe()

,avg_monthly_demand,demand_variability,avg_lead_time_days,lead_time_variability,monthly_reorder_count,stock_turnover_ratio,days_in_inventory,stockout_frequency,backorder_frequency,return_rate,damage_rate,holding_cost_per_unit,unit_cost,reorder_point_breaches,supplier_delay_incidents,current_stock,safety_stock,excess_stock_level,inventory_value,warehouse_demand_pressure_index
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4.000000e+03,4000.00000
mean,331.809250,0.285640,10.301275,0.258738,4.707250,5.944282,65.489750,2.491250,1.938000,0.028485,0.015713,47.709973,804.380267,2.657250,3.239750,317.102000,80.002750,104.915750,2.491254e+05,159.10009
std,228.438284,0.128173,5.592473,0.165963,2.991118,3.804082,56.855528,3.192487,2.503642,0.015560,0.008412,50.174326,741.472968,3.498976,3.615873,136.958627,55.192937,106.302228,2.508303e+05,88.27321
min,1.000000,0.080000,1.000000,0.050000,0.000000,0.200000,4.000000,0.000000,0.000000,0.005000,0.002000,0.520000,20.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000e+00,5.00000
25%,103.000000,0.190000,6.200000,0.130000,2.000000,2.140000,22.000000,0.000000,0.000000,0.017000,0.009000,12.565000,220.160000,0.000000,0.000000,219.000000,27.000000,32.000000,6.278350e+04,82.77000
50%,333.000000,0.260000,9.000000,0.200000,5.000000,6.150000,34.000000,1.000000,1.000000,0.026000,0.015000,33.710000,652.130000,1.000000,2.000000,304.000000,80.000000,60.000000,1.759532e+05,151.79500
75%,523.250000,0.370000,13.400000,0.360000,7.000000,9.140000,106.000000,4.000000,3.000000,0.037000,0.020000,64.495000,1108.817500,4.000000,5.000000,403.000000,122.000000,150.000000,3.498038e+05,228.21000
max,983.000000,0.620000,35.000000,0.720000,14.000000,15.890000,273.000000,15.000000,14.000000,0.080000,0.040000,502.570000,6085.330000,17.000000,18.000000,908.000000,306.000000,622.000000,2.093354e+06,300.00000

In [14]:
df.select_dtypes(include="object").columns

Index(['item_id', 'category', 'subcategory', 'supplier_id', 'warehouse_zone'], dtype='object')

In [15]:
df.select_dtypes(include="number").columns

Index(['avg_monthly_demand', 'demand_variability', 'avg_lead_time_days',
       'lead_time_variability', 'monthly_reorder_count',
       'stock_turnover_ratio', 'days_in_inventory', 'stockout_frequency',
       'backorder_frequency', 'return_rate', 'damage_rate',
       'holding_cost_per_unit', 'unit_cost', 'reorder_point_breaches',
       'supplier_delay_incidents', 'current_stock', 'safety_stock',
       'excess_stock_level', 'inventory_value',
       'warehouse_demand_pressure_index'],
      dtype='object')

In [16]:
df.nunique()

item_id                            4000
category                              8
subcategory                          40
supplier_id                          85
warehouse_zone                        8
avg_monthly_demand                  797
demand_variability                   55
avg_lead_time_days                  284
lead_time_variability                68
monthly_reorder_count                15
stock_turnover_ratio               1239
days_in_inventory                   241
stockout_frequency                   16
backorder_frequency                  15
return_rate                          76
damage_rate                          39
holding_cost_per_unit              3277
unit_cost                          3917
reorder_point_breaches               18
supplier_delay_incidents             19
current_stock                       640
safety_stock                        236
excess_stock_level                  450
inventory_value                    3995
warehouse_demand_pressure_index    3295
dtype: int64

In [17]:
#1. How does average monthly demand vary across different product categories?
df.groupby('category')['avg_monthly_demand'].mean().sort_values(ascending=False)

category
Pharmaceutical    354.012024
Industrial        342.108108
Home & Kitchen    335.700405
Automotive        333.521822
Apparel           331.339216
Stationery        327.657895
Grocery           317.458696
Electronics       311.032129
Name: avg_monthly_demand, dtype: float64

In [18]:
#2. Which product categories show the highest demand variability?
df.groupby('category')['demand_variability'].mean().sort_values(ascending=False)

category
Electronics       0.295663
Grocery           0.291500
Home & Kitchen    0.287652
Automotive        0.287173
Stationery        0.287045
Industrial        0.280637
Pharmaceutical    0.278337
Apparel           0.277902
Name: demand_variability, dtype: float64

In [19]:
#3. Which warehouse zones handle products with the highest average demand?
df.groupby('warehouse_zone')['avg_monthly_demand'].mean().sort_values(ascending=False)

warehouse_zone
D1    344.346939
C2    340.298805
B2    338.925847
C1    330.073260
B1    328.317719
A1    325.836327
D2    324.181633
A2    323.202756
Name: avg_monthly_demand, dtype: float64

In [20]:
#4. Which products have the longest average supplier lead times?
df.groupby('item_id')['avg_lead_time_days'].mean().sort_values(ascending=False).head(10)

item_id
ITM01917    35.0
ITM01309    35.0
ITM00040    35.0
ITM00380    33.9
ITM00926    33.6
ITM02559    32.0
ITM03567    31.9
ITM01665    30.8
ITM01789    30.6
ITM00332    30.6
Name: avg_lead_time_days, dtype: float64

In [22]:
#5. Is high lead-time variability associated with more supplier delay incidents?
df[['lead_time_variability', 'supplier_delay_incidents']].corr()

                          lead_time_variability  supplier_delay_incidents
lead_time_variability                  1.000000                  0.720934
supplier_delay_incidents               0.720934                  1.000000

In [24]:
#6. Which products have the highest stock turnover ratios?
df.groupby('item_id')['stock_turnover_ratio'].mean().sort_values(ascending=False).head(10)

item_id
ITM00427    15.89
ITM02465    15.69
ITM02780    15.34
ITM01419    15.18
ITM02843    15.01
ITM01129    15.00
ITM03703    15.00
ITM03622    15.00
ITM03405    15.00
ITM01766    14.94
Name: stock_turnover_ratio, dtype: float64

In [25]:
#7. Which products remain in inventory for the longest number of days?
df.groupby('item_id')['days_in_inventory'].mean().sort_values(ascending=False).head(10)

item_id
ITM00644    273.0
ITM02773    272.0
ITM03079    268.0
ITM00681    261.0
ITM03723    258.0
ITM01180    252.0
ITM02296    249.0
ITM00548    247.0
ITM01374    246.0
ITM02694    246.0
Name: days_in_inventory, dtype: float64

In [26]:
#8. Is there a relationship between stock turnover ratio and days in inventory?
df[['stock_turnover_ratio', 'days_in_inventory']].corr()

                      stock_turnover_ratio  days_in_inventory
stock_turnover_ratio               1.00000           -0.76298
days_in_inventory                 -0.76298            1.00000

In [27]:
#9. Which products experience the highest stockout frequency?
df.groupby('item_id')['stockout_frequency'].sum().sort_values(ascending=False).head(10)

item_id
ITM02972    15
ITM03758    15
ITM03423    15
ITM03625    15
ITM02850    15
ITM01627    15
ITM02285    15
ITM02256    15
ITM02537    15
ITM01902    15
Name: stockout_frequency, dtype: int64

In [28]:
#10. Are products with high demand variability more likely to experience stockouts?
df[['demand_variability', 'stockout_frequency']].corr()

                    demand_variability  stockout_frequency
demand_variability            1.000000            0.374789
stockout_frequency            0.374789            1.000000

In [29]:
#11. Which products experience frequent backorders?
df.groupby('item_id')['backorder_frequency'].sum().sort_values(ascending=False).head(10)

item_id
ITM01459    14
ITM01872    13
ITM03742    13
ITM03982    13
ITM02144    13
ITM03813    13
ITM02375    13
ITM01994    12
ITM03098    12
ITM03093    12
Name: backorder_frequency, dtype: int64

In [30]:
#12. Is backorder frequency associated with stockout frequency?
df[['backorder_frequency', 'stockout_frequency']].corr()

                     backorder_frequency  stockout_frequency
backorder_frequency             1.000000            0.663003
stockout_frequency              0.663003            1.000000

In [31]:
#13. Which products have the highest reorder-point breaches?
df.groupby('item_id')['reorder_point_breaches'].sum().sort_values(ascending=False).head(10)

item_id
ITM00242    17
ITM00649    17
ITM02342    16
ITM01548    16
ITM03237    16
ITM03247    15
ITM01144    15
ITM02825    15
ITM02270    15
ITM02158    15
Name: reorder_point_breaches, dtype: int64

In [33]:
#14. Do products with frequent reorder-point breaches also have high monthly reorder counts?
df[['reorder_point_breaches', 'monthly_reorder_count']].corr()

                        reorder_point_breaches  monthly_reorder_count
reorder_point_breaches                1.000000               0.342835
monthly_reorder_count                 0.342835               1.000000

In [34]:
#15. Which products have the highest supplier delay incidents?
df.groupby('item_id')['supplier_delay_incidents'].sum().sort_values(ascending=False).head(10)

item_id
ITM01306    18
ITM01806    18
ITM02230    17
ITM00192    17
ITM02516    16
ITM00366    16
ITM02623    16
ITM01128    16
ITM01476    16
ITM03162    15
Name: supplier_delay_incidents, dtype: int64

In [35]:
#16. Is supplier delay associated with increased stockouts or backorders?
df[['supplier_delay_incidents', 'stockout_frequency', 'backorder_frequency']].corr()

,supplier_delay_incidents,stockout_frequency,backorder_frequency
supplier_delay_incidents,1.000000,0.610335,0.569561
stockout_frequency,0.610335,1.000000,0.663003
backorder_frequency,0.569561,0.663003,1.000000

In [36]:
#17. Which products maintain significantly higher safety stock relative to their current stock?
df['safety_stock_ratio'] = df['safety_stock'] / df['current_stock']

In [37]:
df.groupby('item_id')['safety_stock_ratio'].mean().sort_values(ascending=False).head(10)

item_id
ITM01476          inf
ITM02473          inf
ITM01626          inf
ITM01177          inf
ITM03982          inf
ITM03008    18.000000
ITM00494     9.666667
ITM02618     7.050000
ITM01540     3.750000
ITM01987     2.815789
Name: safety_stock_ratio, dtype: float64

In [39]:
#18. Which products have high excess-stock levels?
df.groupby('item_id')['excess_stock_level'].mean().sort_values(ascending=False).head(10)

item_id
ITM01019    622.0
ITM02018    591.0
ITM01376    568.0
ITM02015    542.0
ITM02510    539.0
ITM03530    536.0
ITM02315    503.0
ITM03406    495.0
ITM01172    487.0
ITM03062    484.0
Name: excess_stock_level, dtype: float64

In [40]:
#19. Is excess stock associated with high days in inventory?
df[['excess_stock_level', 'days_in_inventory']].corr()

                    excess_stock_level  days_in_inventory
excess_stock_level            1.000000           0.729002
days_in_inventory             0.729002           1.000000

In [41]:
#20. Which products have the highest inventory value?
df.groupby('item_id')['inventory_value'].sum().sort_values(ascending=False).head(10)

item_id
ITM01254    2093353.52
ITM00156    1993974.96
ITM00707    1905333.80
ITM03470    1902986.23
ITM03719    1775518.85
ITM01078    1699984.38
ITM03086    1687486.24
ITM01183    1632093.78
ITM01599    1590946.24
ITM03736    1563724.36
Name: inventory_value, dtype: float64

In [42]:
#21. Which products have the highest holding cost per unit?
df.groupby('item_id')['holding_cost_per_unit'].mean().sort_values(ascending=False).head(10)

item_id
ITM01254    502.57
ITM02258    477.00
ITM03548    470.56
ITM03736    468.89
ITM01978    427.05
ITM00707    391.89
ITM03591    390.88
ITM02766    380.79
ITM02710    377.69
ITM03664    353.22
Name: holding_cost_per_unit, dtype: float64

In [43]:
#22. Do expensive products tend to have lower or higher stock turnover?
df[['unit_cost', 'stock_turnover_ratio']].corr()

                      unit_cost  stock_turnover_ratio
unit_cost              1.000000             -0.146084
stock_turnover_ratio  -0.146084              1.000000

In [44]:
#23. Which products have the highest return rates?
df.groupby('item_id')['return_rate'].mean().sort_values(ascending=False).head(10)

item_id
ITM02360    0.080
ITM02962    0.080
ITM02624    0.080
ITM02585    0.080
ITM03521    0.079
ITM00824    0.079
ITM02124    0.079
ITM00372    0.079
ITM00890    0.079
ITM00463    0.079
Name: return_rate, dtype: float64

In [45]:
#24. Which products have the highest damage rates?
df.groupby('item_id')['damage_rate'].mean().sort_values(ascending=False).head(10)

item_id
ITM01406    0.04
ITM00703    0.04
ITM02628    0.04
ITM01590    0.04
ITM01161    0.04
ITM02278    0.04
ITM02814    0.04
ITM01472    0.04
ITM02056    0.04
ITM03289    0.04
Name: damage_rate, dtype: float64

In [46]:
#25. Are high return and damage rates concentrated in particular categories or warehouse zones?
df.groupby('category')[['return_rate', 'damage_rate']].mean().sort_values('return_rate', ascending=False)

                return_rate  damage_rate
category
Electronics        0.029620     0.015857
Home & Kitchen     0.029095     0.015636
Automotive         0.028767     0.015972
Industrial         0.028432     0.015564
Grocery            0.028346     0.015689
Pharmaceutical     0.028216     0.014996
Stationery         0.027907     0.016324
Apparel            0.027494     0.015663

In [47]:
df.groupby('warehouse_zone')[['return_rate', 'damage_rate']].mean().sort_values('return_rate', ascending=False)

                return_rate  damage_rate
warehouse_zone
D2                 0.029318     0.015727
B1                 0.029092     0.015939
C2                 0.028894     0.015542
A2                 0.028528     0.016478
B2                 0.028460     0.015769
A1                 0.028317     0.016032
C1                 0.027777     0.014905
D1                 0.027563     0.015376

In [48]:
#26. Which products have the highest warehouse demand pressure index?
df.groupby('item_id')['warehouse_demand_pressure_index'].mean().sort_values(ascending=False).head(10)

item_id
ITM02153    300.0
ITM03378    300.0
ITM03318    300.0
ITM03314    300.0
ITM03307    300.0
ITM03305    300.0
ITM03299    300.0
ITM03295    300.0
ITM00825    300.0
ITM02003    300.0
Name: warehouse_demand_pressure_index, dtype: float64